---
title: "cumulative and facet example"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### sample code to graph cumulative summations
#### plot height growth of seedlings through time, facet by species
#### code from C:\Users\pjs23\Documents\R\ntres6940\Lessons-pdf-6940-data-science\Lesson 9_ ggplot part 2.pdf

```{r}

library(tidyverse)
# read datafile
# 
coronavirus <- read_csv('https://raw.githubusercontent.com/RamiKrispin/coronavirus/master/csv/coronavirus.csv', col_types = cols(province = col_character()))


#graph with facet by country
#
coronavirus %>%
filter(type == "confirmed", country %in% top10_countries) %>%
group_by(country, date) %>%
summarize(total_cases = sum(cases)) %>%
ggplot(mapping = aes(x = date, y = total_cases)) +
geom_line() +
facet_wrap(~country)

#cumulative of quantitative variable
#
coronavirus %>%
filter(type == "confirmed", country %in% top10_countries) %>%
group_by(country) %>%
arrange(date) %>%
mutate(cum_count = cumsum(cases)) %>%
ggplot(mapping = aes(x = date, y = cum_count, color = country)) +
geom_line()

```

