---
title: "test sap syrup"
author: "Peter Smallidge"
date: "10/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Read libraries

```{r}

# Library:
#       tidyverse, skimr
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(tidyr)
library(skimr)
library(readr)


#
# ALT plus hypen = <- (within chunk)
# ctrl plus shift plus m = %>% 
# ctrl + ALT + I = insert chunk
# filter rows, select columns
# RMD comment = <!-- comment -->


```
### Reading Static (single measurement) Variables


```{r}
crown <- read_csv("lumbershed.static.2020.csv", 
    col_types = cols(seq = col_character(), 
        tag = col_integer(), ftg2017 = col_integer()))
crown <- crown %>% 
  select(-ftg2017_1) 


head(crown, n=10)

```


### Reading Annual SSC and Sap Volume Measurements

```{r}

## calculate the dbhI to allow graphing of minimally acceptable growth rate


syrup_wide <- read_csv("lumbershed.annual.2020.csv",
                       col_types = cols(seq = col_character(),
                                        tag = col_integer())
                       ) %>% 
  mutate(vigor_base2017 = (dbh2017^2 * 0.005454 * 144),
         ba2016 = (dbh2016^2 * 0.005454 * 144),
         ba2017 = (dbh2017^2 * 0.005454 * 144),
         ba2018 = (dbh2018^2 * 0.005454 * 144),
         ba2019 = (dbh2019^2 * 0.005454 * 144),
         ba2020 = (dbh2020^2 * 0.005454 * 144),
         bai2017 = (ba2017 - ba2016),
         bai2018 = (ba2018 - ba2017),
         bai2019 = (ba2019 - ba2018),
         bai2020 = (ba2020 - ba2019),
         rbai2017 = (bai2017 / vigor_base2017*100),
         rbai2018 = (bai2018 / vigor_base2017*100),
         rbai2019 = (bai2019 / vigor_base2017*100),
         rbai2020 = (bai2020 / vigor_base2017*100)
         )%>% 
  select(-sap2020.long, -ssc2020.long, -syrup2020.long) %>% 
  select(seq, tag, dbh2016, ba2016, dbh2017, ba2017, dbh2018, ba2018, everything())


head(syrup_wide, n=10)

```


### Pivot wide to long

```{r}
#tree diameter data, pivot long
#
#
# dbh data, pivot long
diam <-  
  pivot_longer(syrup_wide, c(dbh2016, dbh2017, dbh2018, dbh2019, dbh2020), names_to = 'year', values_to = 'dbh') %>%  # the "names_to" command uses the variables dbh2016, etc as the data within a new
  # variable "year" The values_to command places the data of the variables dbh2016 etc within a new
  # variable "dbh"
  select(seq, tag, dbh, year, vigor_base2017)

diam$year[diam$year == "dbh2016"] <- "2016"  # recode the values to be the year, not "dbhyear"
diam$year[diam$year == "dbh2017"] <- "2017"
diam$year[diam$year == "dbh2018"] <- "2018"
diam$year[diam$year == "dbh2019"] <- "2019"
diam$year[diam$year == "dbh2020"] <- "2020"

diam$year <- as.integer(diam$year) # convert the variable year to integer from character
head(diam, n=10)


# basal area data, pivot long
basal <-  
  pivot_longer(syrup_wide, c(ba2016, ba2017, ba2018, ba2019, ba2020), names_to = 'year', values_to = 'basal_area') %>% 
  select(seq, tag, basal_area, year)

basal$year[basal$year == "ba2016"] <- "2016"
basal$year[basal$year == "ba2017"] <- "2017"
basal$year[basal$year == "ba2018"] <- "2018"
basal$year[basal$year == "ba2019"] <- "2019"
basal$year[basal$year == "ba2020"] <- "2020"

basal$year <- as.integer(basal$year)
head(basal, n=10)



# BAI = basal area increment data, pivot long
increment <-  
  pivot_longer(syrup_wide, c(bai2017, bai2018, bai2019, bai2020), names_to = 'year', values_to = 'bai') %>% 
  select(seq, tag, bai, year)


increment$year[increment$year == "bai2017"] <- "2017"
increment$year[increment$year == "bai2018"] <- "2018"
increment$year[increment$year == "bai2019"] <- "2019"
increment$year[increment$year == "bai2020"] <- "2020"

increment$year <- as.integer(increment$year)
head(increment, n=10)



# rBAI = relative basal area increment data (AKA vigor), pivot long
vig01 <-  
  pivot_longer(syrup_wide, c(rbai2018, rbai2019, rbai2020), names_to = 'year', values_to = 'rbai') %>% 
  select(seq, tag, rbai, year)

vig01$year[vig01$year == "rbai2017"] <- "2017"
vig01$year[vig01$year == "rbai2018"] <- "2018"
vig01$year[vig01$year == "rbai2019"] <- "2019"
vig01$year[vig01$year == "rbai2020"] <- "2020"

vig01$year <- as.integer(vig01$year)
head(vig01, n=10)




# sap volume data (gallons) pivot long
sap <- 
  pivot_longer(syrup_wide, c(sap2017, sap2018, sap2019, sap2020), names_to = 'year', values_to = "sap_vol") %>% 
  select(seq, tag, sap_vol, year)

sap$year[sap$year == "sap2017"] <- "2017"
sap$year[sap$year == "sap2018"] <- "2018"
sap$year[sap$year == "sap2019"] <- "2019"
sap$year[sap$year == "sap2020"] <- "2020"

sap$year <- as.integer(sap$year)
head(sap, n=10)




# SSC (sap sugar concentration) data pivot long
sugar <- 
  pivot_longer(syrup_wide, c(ssc2017, ssc2018, ssc2019, ssc2020), names_to = 'year', values_to = "ssc") %>% 
  select(seq, tag, ssc, year)

sugar$year[sugar$year == "ssc2017"] <- "2017"
sugar$year[sugar$year == "ssc2018"] <- "2018"
sugar$year[sugar$year == "ssc2019"] <- "2019"
sugar$year[sugar$year == "ssc2020"] <- "2020"

sugar$year <- as.integer(sugar$year)
head(sugar, n=10)



# Syrup (maple syrup volume in gallons) data pivot long
syrup <- 
  pivot_longer(syrup_wide, c(syrup2017, syrup2018, syrup2019, syrup2020), names_to = 'year', values_to = "syrup_vol") %>% 
  select(seq, tag, syrup_vol, year)

syrup$year[syrup$year == "syrup2017"] <- "2017"
syrup$year[syrup$year == "syrup2018"] <- "2018"
syrup$year[syrup$year == "syrup2019"] <- "2019"
syrup$year[syrup$year == "syrup2020"] <- "2020"

syrup$year <- as.integer(syrup$year)
head(syrup, n=10)



```

### full join of the data files:
### diam, basal, increment, vigor, sap, sugar, syrup
### by seq, tag, year


```{r}

annual <- diam %>% 
  full_join(basal, by = c("seq", "tag", "year")) %>% 
  full_join(increment, by = c("seq", "tag", "year")) %>% 
  full_join(vig01, by = c("seq", "tag", "year")) %>% 
  full_join(sap, by = c("seq", "tag", "year")) %>% 
  full_join(sugar, by = c("seq", "tag", "year")) %>% 
  full_join(syrup, by = c("seq", "tag", "year")) %>% 
  full_join(crown, by = c("seq", "tag")) %>% 
  mutate(numb = 1) %>% 
  select(seq, tag, year, numb, everything())

# the above code creates a new datafile (df) called "annual" based on the diam df
# the "full_join" command adds the df BASAL to df DIAM by aligning the columns
# seq, tag, and year. Each addition df is joined. The "full_join" retains all rows, even if there 
# are missing values.

head(annual, n=10)

annual %>% 
  write_csv(path = "annual_growth_sap.csv")

library(knitr)
# kable(annual)  ## this code works
```

## Assess Tree Vigor and Performance
```{r}
vig_test <- annual %>% 
  select(seq, tag, numb, dbh, year, basal_area, bai, rbai, sap_vol, ssc, syrup_vol, 
         crown.class, pct.open.jan.2019, FTG2019, crown.area.2017) %>%
    filter(year > 2016) %>% 
  group_by(FTG2019, year) %>% 
  summarize(
    n = sum(is.na (numb)),
    n2 = n(),
    dbh_med = median(dbh),
    dbh_mean = mean(dbh),
    BA = mean(basal_area),
    PCTopen = mean(pct.open.jan.2019),
    sap_gal = mean((sap_vol))
  )
head(vig_test, n=20)
```



```{r}
vig02 <- annual %>% 
  select(seq, tag, dbh, year, basal_area, bai, rbai, sap_vol, ssc, syrup_vol, 
         crown.class, pct.open.jan.2019, FTG2019, crown.area.2017) %>% 
    filter(year > 2016) %>% 
  group_by(FTG2019, year) %>% 
  summarize(
    n = n(),
    vigor = mean(rbai),
    dbh_med = median(dbh),
    dbh_mean = mean(dbh),
    BA = mean(basal_area),
    bai = mean(bai),
    PCTopen = mean(pct.open.jan.2019),
    crown.area = mean(crown.area.2017),
    sap_gal = mean(is.na (sap_vol)),
    ssc = mean(is.na (ssc)),
    syrup_gal = mean(is.na (syrup_vol))
  )

head(vig02)

vig02 %>% 
  write_csv(path = "summary-vigor-syrup-annual.csv")

## NEXT - rerun the group_by / summarize to sort for 2019 and 2020 data.
## rerun the analysis
## 
## run ggplot x =rbai, y = various tree metrics, size = year

# df=vig03 = post harvest data by FTG rating


vig03 <- annual %>% 
  select(seq, tag, dbh, year, basal_area, bai, rbai, sap_vol, ssc, syrup_vol, 
         crown.class, pct.open.jan.2019, FTG2019, crown.area.2017) %>% 
  filter(year == "2019" | year == "2020") %>% 
  group_by(FTG2019) %>% 
  summarize(
    n = n(),
    vigor = mean(rbai),
    dbh_med = median(dbh),
    dbh_mean = mean(dbh),
    BA = mean(basal_area),
    bai = mean(bai),
    PCTopen = mean(pct.open.jan.2019),
    crown.area = mean(crown.area.2017),
    sap_gal = mean(sap_vol),
    ssc = mean(ssc),
    syrup_gal = mean(syrup_vol)
  )

head(vig03)

vig03 %>% 
  write_csv(path = "summary-vigor-syrup-post-harvest.csv")


# df=vig04 = post harvest data by FTG and crown strata
vig04 <- annual %>% 
  select(seq, tag, dbh, year, basal_area, bai, rbai, sap_vol, ssc, syrup_vol, 
         crown.class, strata.post, pct.open.jan.2019, FTG2019, crown.area.2017) %>% 
  filter(year == "2019" | year == "2020") %>% 
  group_by(strata.post, FTG2019) %>% 
  summarize(
    n = n(),
    vigor = mean(rbai),
    dbh_med = median(dbh),
    dbh_mean = mean(dbh),
    BA = mean(basal_area),
    bai = mean(bai),
    PCTopen = mean(pct.open.jan.2019),
    crown.area = mean(crown.area.2017),
    sap_gal = mean(sap_vol),
    ssc = mean(ssc),
    syrup_gal = mean(syrup_vol)
  )

head(vig04)

vig04 %>% 
  write_csv(path = "summary-vigor-syrup-post-harvest-crown-class.csv")

```



### Run ggplot of BAI x tree output 

```{r}


## plot code example 1
#ggplot(data = annual) +
#  geom_point(mapping = aes(x= bai, y = ssc, color = year, size = dbh), shape = 1) +
#  geom_smooth(mapping = aes(x = bai, y = ssc), method = lm, se = FALSE) 
  

# equivalent to plot code example 1
#ggplot(data = annual, mapping = aes(x = bai, y = ssc)) +
#  geom_point(mapping = aes(color = year, size = dbh), method = lm, se = FALSE, shape = 1) +
#  geom_smooth() +
#  theme_bw()

dir.create("figures")

  ### BAI and SSC  

ggplot((data = syrup_wide), 
       mapping = aes(x=bai2019, y = ssc2020)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Basal Area Increment 2019 (sq. in.)",
    y = "Sap Sugar Concentration 2020 (%)",
    title = "Tree Growth and SSC",
    subtitle = "Arnot Forest"
  )

  ggsave("figures/bai2019-ssc2020.jpg")

  
ggplot((data = syrup_wide), 
       mapping = aes(x=bai2018, y = ssc2019)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Basal Area Increment 2018 (sq. in.)",
    y = "Sap Sugar Concentration 2019 (%)",
    title = "Tree Growth and SSC",
    subtitle = "Arnot Forest"
  )

  ggsave("figures/bai2018-ssc2019.jpg")

  
  ### BAI and Sap Volume  
  ggplot((data = syrup_wide), 
       mapping = aes(x=bai2017, y = sap2018)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Basal Area Increment 2017 (sq. in.)",
    y = "Sap Volume 2018 (gallons)",
    title = "Tree Growth and Sap Volume",
    subtitle = "Arnot Forest"
  )

  ggsave("figures/bai2017-sap2018.jpg")
  
  ggplot((data = syrup_wide), 
       mapping = aes(x=bai2018, y = sap2019)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Basal Area Increment 2018 (sq. in.)",
    y = "Sap Volume 2019 (gallons)",
    title = "Tree Growth and Sap Volume",
    subtitle = "Arnot Forest"
  )

  ggsave("figures/bai2018-sap2019.jpg")


  
ggplot((data = syrup_wide), 
       mapping = aes(x=bai2019, y = sap2020)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Basal Area Increment 2019 (sq. in.)",
    y = "Sap Volume 2020 (gallons)",
    title = "Tree Growth and Sap Volume",
    subtitle = "Arnot Forest"
  )

  ggsave("figures/bai2019-sap2020.jpg")
  

  
  ### BAI and Syrup Volume  
  
  ggplot((data = syrup_wide), 
       mapping = aes(x=bai2018, y = syrup2019)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Basal Area Increment 2018 (sq. in.)",
    y = "Syrup Volume 2019 (gallons)",
    title = "Tree Growth and Syrup Volume",
    subtitle = "Arnot Forest"
  )

  ggsave("figures/bai2018-syrup2019.jpg")


  
ggplot((data = syrup_wide), 
       mapping = aes(x=bai2019, y = syrup2020)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Basal Area Increment 2019 (sq. in.)",
    y = "Syrup Volume 2020 (gallons)",
    title = "Tree Growth and Syrup Volume",
    subtitle = "Arnot Forest"
  )

  ggsave("figures/bai2019-syrup2020.jpg")

  
  ### rBAI and Sap Sugar Concentration  
  
  ggplot((data = syrup_wide), 
       mapping = aes(x=rbai2018, y = ssc2019)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Vigor (rBAI) 2018 (%)",
    y = "Sap Sugar Concentration 2019 (%)",
    title = "Tree Vigor and Sap Sugar Concentration",
    subtitle = "Arnot Forest"
  )

  ggsave("figures/rbai2018-ssc2019.jpg")


  
ggplot((data = syrup_wide), 
       mapping = aes(x=rbai2019, y = ssc2020)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Vigor (rBAI) 2019 (%)",
    y = "Sap Sugar Concentration 2020 (%)",
    title = "Tree Vigor and Sap Sugar Concentration",
    subtitle = "Arnot Forest"
  )

  ggsave("figures/rbai2019-ssc2020.jpg")
  
  
  
  
  ### rBAI and Sap Volume  
  
  ggplot((data = syrup_wide), 
       mapping = aes(x=rbai2018, y = sap2019)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Vigor (rBAI) 2018 (%)",
    y = "Sap Volume 2019 (gallons)",
    title = "Tree Vigor and Sap Volume",
    subtitle = "Arnot Forest"
  )

  ggsave("figures/rbai2018-sap2019.jpg")


  
ggplot((data = syrup_wide), 
       mapping = aes(x=rbai2019, y = sap2020)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Vigor (rBAI) 2019 (%)",
    y = "Sap Volume 2020 (gallons)",
    title = "Tree Vigor and Sap Volume",
    subtitle = "Arnot Forest"
  )

  ggsave("figures/rbai2019-sap2020.jpg")
  
    
  
  ### rBAI and Syrup Volume  
  
  ggplot((data = syrup_wide), 
       mapping = aes(x=rbai2018, y = syrup2019)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Vigor (rBAI) 2018 (%)",
    y = "Syrup Volume 2019 (gallons)",
    title = "Tree Vigor and Syrup Volume",
    subtitle = "Arnot Forest"
  )

  ggsave("figures/rbai2018-syrup2019.jpg")


  
ggplot((data = syrup_wide), 
       mapping = aes(x=rbai2019, y = syrup2020)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Vigor (rBAI) 2019 (%)",
    y = "Syrup Volume 2020 (gallons)",
    title = "Tree Vigor and Syrup Volume",
    subtitle = "Arnot Forest"
  )

  ggsave("figures/rbai2019-syrup2020.jpg")
  
  
# R and p-value https://stackoverflow.com/questions/7549694/add-regression-line-equation-and-r2-on-graph?noredirect=1&lq=1 
# 
  
  
  
  

```



### GGPLOT of column data 
#### Crown Class, FTG, etc.


```{r}
annual %>% 
  select(crown.area.2017, strata.pre, FTG2019) %>% 
  group_by(FTG2019, strata.pre) %>% 
  summarize(crown.area = mean(crown.area.2017)) %>% 
  ggplot() +
  geom_col(aes(x=FTG2019, y=crown.area, fill = strata.pre), color = "black", position = "dodge2") +
  theme_classic()+
  labs(
    x = "Crown Free-To-Grow Rating in 2019",
    y = "Crown Area (sq. ft)",
    title = "Crown Area Among Treatments"
  )

  ggsave("figures/column-crown-area-FTG-strata.jpg")

  
annual %>% 
  filter(year == "2017" | year == "2018") %>% 
  mutate(year = as.character(year)) %>% 
  select(bai, strata.pre, year) %>% 
  group_by(year, strata.pre) %>% 
  summarize(bai = mean(bai)) %>% 
  ggplot()+
  geom_col(aes(x=year, y = bai, fill = strata.pre), color = "red", position = "dodge2")+
  theme_classic()+
  labs(
    x = "Year",
    y = "Basal Area Increment (sq inches)",
    title = "Average Growth Pre-Harvest (2017 & 2018)"
  )

  ggsave("figures/column-BAI-FTG-strata.jpg")
  
  
  
  
annual %>% 
  filter(year == "2019" | year == "2020") %>% 
  select(bai, strata.post, FTG2019) %>% 
  group_by(FTG2019, strata.post) %>% 
  summarize(bai = mean(bai)) %>% 
  ggplot()+
  geom_col(aes(x=FTG2019, y = bai, fill = strata.post), color = "red", position = "dodge2")+
  theme_classic()+
  labs(
    x = "Crown Free-to-Grow Rating (2019)",
    y = "Basal Area Increment (sq inches)",
    title = "Average Growth Response Post-Harvest (2019 & 2020)"
  )

  ggsave("figures/column-BAI-FTG-strata.jpg")


# Vigor by Crown class (2017 vs. 2019)and by year
annual %>%
  filter(year > 2017) %>% 
  mutate(year_c = as.character(year)) %>% 
  select(rbai, strata.post, year_c) %>% 
  group_by(year_c, strata.post) %>% 
  summarize(rbai = mean(rbai)) %>% 
  ggplot() +
  geom_col(aes(x=year_c, y = rbai, fill = strata.post), position = "dodge2") +
  theme_classic() +
  labs(
    x = "Year and Post-Harvest Crown Class",
    y = "Tree Vigor (rBAI as % of 2017 Basal Area)",
    title = "Tree Vigor Response to Crown Class and Thinning",
    subtitle = "Harvest completed August 2018"
  )
  
  ggsave("figures/column-rBAI-year-crownclass2019.jpg")


  annual %>%
  mutate(year = as.character(year)) %>% 
  filter(year > 2017) %>% 
  select(rbai, strata.pre, year) %>% 
  group_by(year, strata.pre) %>% 
  summarize(rbai = mean(rbai)) %>% 
  ggplot() +
  geom_col(aes(x=year, y = rbai, fill = strata.pre), position = "dodge2") +
  theme_classic() +
  labs(
    x = "Year and Pre-Harvest Crown Class",
    y = "Tree Vigor (rBAI as % of 2017 Basal Area)",
    title = "Tree Vigor Response to Crown Class and Thinning",
    subtitle = "Harvest completed August 2018"
  )
  
  ggsave("figures/column-rBAI-year-crownclass2017.jpg")

  

```




<!-- comment (11/30/2020)-->
<!-- I need to offset the year of growth by one -->
<!-- such that tree output (e.g., ssc) of year i is associated with growth in year i-1 -->
<!-- add (+1) to the year after selecting for BA, BAI and rBAI  -->
<!-- full join the adjusted year to the output df by year -->
<!-- rename year to "year_sap" reflecting the year aligns with sap -->
<!-- print the columns to confirm the action -->



```{r}
growth_plus_one <- annual %>% 
  select(tag, year, dbh, basal_area, bai, rbai) %>% 
  mutate(year = year + 1) %>% 
     # increment up the growth data of a year to align with the next year's sap data
    filter(year<2021) 
     # remove the growth data of the most recent year which lacks  corresponding sap data

head(growth_plus_one, n=10)

year_adjusted <- annual %>% 
  select(-c(dbh, basal_area, bai, rbai, vigor_base2017)) %>%  #remove growth variables
  full_join(growth_plus_one, by = c("tag", "year")) %>% 
  select(seq, tag, dbh, year, basal_area, bai, rbai, everything()) %>% 
    #reorder sequence of variables
  rename(year_sap = year)
  

head(year_adjusted, n=10)


```


```{r}

### general tree patterns
### 

ggplot((data = year_adjusted), 
       mapping = aes(x=basal_area, y = rbai)) +
  geom_point((mapping = aes(size = crown.area.2017, color = strata.post))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(50,200)+
  labs(
    x = "Basal Area  (sq. in.)",
    y = "Vigor (rBAI as % of 2017 BA)",
    title = "Tree Growth and SSC",
    subtitle = "Arnot Forest, pg1"
  )

  ggsave("figures/basal_area-rbai.jpg")

  
ggplot((data = year_adjusted), 
       mapping = aes(x=crown.area.2017, y = bai)) +
  geom_point((mapping = aes(size = 3, color = strata.post))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  ylim(0,10)+
  xlim(0,1000)+
  labs(
    x = "Crown Area in 2017 (sq. ft.)",
    y = "Basal Area Increment (sq. in.)",
    title = "Tree Growth Patterns",
    subtitle = "Arnot Forest, pg2"
  )

  ggsave("figures/basal_area_increment_crown_area.jpg")  
  
  
  
ggplot((data = year_adjusted), 
       mapping = aes(x=dbh, y = syrup_vol)) +
  geom_point((mapping = aes(size = crown.area.2017, color = strata.post))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,25)+
  labs(
    x = "Diameter Breast Height = dbh  ( in.)",
    y = "Syrup Volume (gal)",
    title = "Tree Size and Syrup Production",
    subtitle = "Arnot Forest, pg3"
  )

  ggsave("figures/dbh-syrup.jpg")
  
  
  
ggplot((data = year_adjusted), 
       mapping = aes(x=dbh, y = ssc)) +
  geom_point((mapping = aes(size = crown.area.2017, color = strata.post))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,25)+
  labs(
    x = "Diameter Breast Height = dbh  ( in.)",
    y = "Sap Sugar Concentration (%)",
    title = "Tree Size and Syrup Production",
    subtitle = "Arnot Forest, pg4"
  )

  ggsave("figures/dbh-ssc.jpg")
  
  
  
  
ggplot((data = year_adjusted), 
       mapping = aes(x=dbh, y = syrup_vol)) +
  geom_point((mapping = aes(size = crown.area.2017, color = strata.post))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(5,22)+
  labs(
    x = "Diameter Breast Height  (dbh, in.)",
    y = "Syrup Volume (gal)",
    title = "Tree Size and Syrup Production",
    subtitle = "Arnot Forest, pg5"
  )

  ggsave("figures/dbh-syrup.jpg")  
  
  
  
  ggplot((data = year_adjusted), 
       mapping = aes(x=basal_area, y = syrup_vol)) +
  geom_point((mapping = aes(size = crown.area.2017, color = strata.post))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
 # xlim(0,25)+
  labs(
    x = "Basal Area  (sq in.)",
    y = "Syrup Volume (gal)",
    title = "Tree Size and Syrup Production",
    subtitle = "Arnot Forest, pg5b"
  )

  ggsave("figures/basal_area-syrup.jpg") 
  
  
### graphs for BAI
###

ggplot((data = year_adjusted), 
       mapping = aes(x=bai, y = ssc)) +
  geom_point((mapping = aes(size = crown.area.2017, color = year_sap))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Basal Area Increment (sq. in.)",
    y = "Sap Sugar Concentration (%)",
    title = "Tree Growth and SSC",
    subtitle = "Arnot Forest, pg6"
  )

  ggsave("figures/bai-ssc.jpg")

 
  ggplot((data = year_adjusted),
       mapping = aes(x=bai, y = sap_vol)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Basal Area Increment (sq. in.)",
    y = "Sap Volume (gal)",
    title = "Tree Growth 2017-2020 and SSC",
    subtitle = "Arnot Forest, pg7"
  )

  ggsave("figures/bai-sap-volume.jpg")

  
  
preharvest <- year_adjusted %>% 
  filter(year_sap < 2019)
#head(preharvest, n=20)

  ggplot((data = preharvest),
       mapping = aes(x=bai, y = sap_vol)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Basal Area Increment (sq. in.)",
    y = "Sap Volume (gal)",
    title = "Pre-Harvest Tree Growth and Sap Volume",
    subtitle = "Arnot Forest, pg7a"
  )

  ggsave("figures/PRE-harvest-bai-sap-volume.jpg")  
  
  
  ggplot((data = preharvest),
       mapping = aes(x=bai, y = syrup_vol)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Basal Area Increment (sq. in.)",
    y = "Syrup Volume (gal)",
    title = "Pre-Harvest Tree Growth and Syrup Volume",
    subtitle = "Arnot Forest, pg7b"
  )

  ggsave("figures/PRE-harvest-bai-syrup-volume.jpg")  
  
  
  
  ggplot((data = preharvest),
       mapping = aes(x=bai, y = ssc)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Basal Area Increment (sq. in.)",
    y = "Sap Sugar Concentration (%)",
    title = "Pre-Harvest Tree Growth and Sap Sugar Concentration",
    subtitle = "Arnot Forest, pg7c"
  )

  ggsave("figures/PRE-harvest-bai-ssc.jpg")    
  
  
  
  
    ggplot((data = year_adjusted), 
       mapping = aes(x=bai, y = syrup_vol)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Basal Area Increment (sq. in.)",
    y = "Syrup Volume (gal)",
    title = "Tree Growth and Syrup Production",
    subtitle = "Arnot Forest, pg8"
  )

  ggsave("figures/bai-syrup-volume.jpg")

  
  ### graphs for VIGOR
  ### 
  
  ggplot((data = year_adjusted), 
       mapping = aes(x=rbai, y = ssc)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,7.5)+
  labs(
    x = "Vigor (rBAI = BAI % BA 2017 sq. in.)",
    y = "Sap Sugar Concentration (%)",
    title = "Tree Growth and SSC",
    subtitle = "Arnot Forest, pg9"
  )

  ggsave("figures/vigor-ssc.jpg")
  
  
    ggplot((data = year_adjusted), 
       mapping = aes(x=rbai, y = sap_vol)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,7.5)+
  labs(
    x = "Vigor (rBAI = BAI % BA 2017 sq. in.)",
    y = "Sap Volume (gal)",
    title = "Tree Growth and SSC",
    subtitle = "Arnot Forest, pg10"
  )

  ggsave("figures/vigor-sap-volume.jpg")

  
      ggplot((data = year_adjusted), 
       mapping = aes(x=rbai, y = syrup_vol)) +
  geom_point((mapping = aes(size = crown.area.2017))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,7.5)+
  labs(
    x = "Vigor (rBAI = BAI % BA 2017 sq. in.)",
    y = "Syrup Volume (gal)",
    title = "Tree Growth and SSC",
    subtitle = "Arnot Forest, pg11"
  )

  ggsave("figures/vigor-syrup-volume.jpg")
  
  
  
  ### post harvest
  ### 
  
  post <- year_adjusted %>% 
    filter(year_sap %in% c("2019", "2020"))
    
  ggplot((data = post), 
       mapping = aes(x=pct.open.jan.2019, y = ssc)) +
  geom_point((mapping = aes(size = bai))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,360)+
  labs(
    x = "Percent of Crown Open (%)",
    y = "Sap Sugar Concentration (%)",
    title = "Crown Exposure and Sap Sugar Concentration",
    subtitle = "Arnot Forest, pg12"
  )

  ggsave("figures/post-harvest-PCT-open-crown-ssc.jpg")
  
  
  
    ggplot((data = post), 
       mapping = aes(x=pct.open.jan.2019, y = sap_vol)) +
  geom_point((mapping = aes(size = bai))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,360)+
  labs(
    x = "Percent of Crown Open (%)",
    y = "Sap Volume (gal)",
    title = " Post-Harvest Tree Growth and Sap Volume",
    subtitle = "Arnot Forest, pg13"
  )

  ggsave("figures/post-harvest-PCT-open-crown-sap-volume.jpg")
  
  
    ggplot((data = post), 
       mapping = aes(x=pct.open.jan.2019, y = bai)) +
  geom_point((mapping = aes(size = 3))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,360)+
  labs(
    x = "Percent of Crown Open (%)",
    y = "Basal Area Increment (sq. in.)",
    title = " Post-Harvest Tree Growth and Tree Growth",
    subtitle = "Arnot Forest, pg14"
  )

  ggsave("figures/post-harvest-PCT-open-crown-bai.jpg")
  
  
  
    ggplot((data = post), 
       mapping = aes(x=bai, y = sap_vol)) +
  geom_point((mapping = aes(color = pct.open.jan.2019, size = 3))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Basal Area Increment (sq. in.)",
    y = "Sap Volume (gal)",
    title = " Post-Harvest Tree Growth and Sap Volume",
    subtitle = "Arnot Forest, pg15"
  )

  ggsave("figures/post-harvest-bai-sap-volume.jpg")
    
  
    ggplot((data = post), 
       mapping = aes(x=bai, y = syrup_vol)) +
  geom_point((mapping = aes(color = FTG2019, size = strata.post))) +
  geom_smooth(method = lm, se = FALSE) +
  stat_cor(label.x.npc="left",label.y.npc = "top", 
           method="pearson", r.digits=2, p.digits=4, p.accuracy = 0.001)+
  stat_regline_equation(label.x.npc="center",label.y.npc = "top")+  
          #stat_cor and stat_regline within library(ggpubr)
  theme_classic()+
  xlim(0,10)+
  labs(
    x = "Basal Area Increment (sq. in)",
    y = "Syrup Volume (gal)",
    title = " Post-Harvest Tree Growth and Syrup Volume",
    subtitle = "Arnot Forest, pg16"
  )

  ggsave("figures/post-harvest-bai-syrup-volume.jpg")
  
  
```


